### ISSUE TITLE
[Typos] Fedora copr install

### ISSUE THREAD

**Issue by bagong** [MrDuartePT/LLL-pkg-repo#1]
**Problem Descripition**
Not a biggie at all, but there are two typos for people doing the copr install following your hints

- it's not `sudo dnf uninstall` but `sudo dnf remove` in the readme
- the `cp /usr/share/lenovoLegionLinux` to /etc/...` requires a `-r` because it's a folder copy

**Model and Debug Info**

independent

Distribution: Fedora any
Model name: independent
CPU model: ??? (e.g. AMD Ryzen 7 5800H)
GPU model: ??? (e.g NVIDIA RTX 3700)
Keyboard backlight: ??? (RGB, single color with off/on, single color with off/medium/bright)
Light in lid or logo: ??? (yes/no)
Light at IO-Ports at back: ??? (yes/no)

Output of `sudo dmidecode -t system`. Please remove Serial Number and UUID for privacy:
```text
???
```

Output of `sudo dmidecode -t bios`:
```text
???
```

Output of `sudo cat /sys/kernel/debug/legion/fancurve`:
```text
???
```

**Comment by MrDuartePT** [comment]
> * the `cp /usr/share/lenovoLegionLinux` to /etc/...`requires a`-r` because it's a folder copy

This is required to commit in LenovoLegionLinux to solve the typo I will solve it when I commit again in the project
